spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_first?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 777777
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 10000

  redis:
    database: ${REDIS_DATABASE:2}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

swagger:
  enable: true

server:
  port: 8099

shareService:
  userCenter:
    jwtTokenKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMgQBgLiNmB/OtL3HROM5cObn+VbMjwZDMy+qKERTpytgrgmyk2hTJg2xIGdK1VVBYgWKNK2GlXl5JnAX1JYWicCAwEAAQ==
    tokenHeader: X-JWT-TOKEN
    excludeUrls: /swagger-resources,/webjars,/v2/api-docs,/swagger-ui.html,/actuator/health