apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: omp-sample-service
  name: omp-sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: omp-sample-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: omp-sample-service
    spec:
      containers:
      - image: 459448595428.dkr.ecr.cn-north-1.amazonaws.com.cn/omp-sample-service:0.01
        name: omp-sample-service
        ports:
        - containerPort: 8080
          name: userport
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: PROFILE_NAME
          valueFrom:
            configMapKeyRef:
              name: cm-ss-profile
              key: PROFILE_NAME
        - name: PROPS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: secret-stage-git
              key: PROPS_ENCRYPTION_KEY
        - name: NEW_RELIC_APP_NAME
          value: "omp-sample-service-staging"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: secret-newrelic
              key: LICENSE_KEY
